require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'P2PSimulcast' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'P2PSimulcastTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'P2PSimulcast-tvOS' do
  # Pods for P2PSimulcast-tvOS

  target 'P2PSimulcast-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
