# shiguredo/sora-ios-sdk-specs を追加します。
source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

# ビルドに失敗する可能性があるため、 use_frameworks! の使用は推奨しません。
# use_frameworks!

node_modules_path = '../node_modules'

target 'HelloSora' do

  # 以下の 2 行を追加しないとビルドに失敗する可能性があります。
  pod 'yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"

  # このコメントの直下の行に、追加のreact-nativeネイティブモジュールがインストールされていきます。本ライブラリも以下に追加されます。
  # Add new pods below this line

end

# `libReact.a` の衝突を回避する処理を記述します。
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
