# shiguredo/sora-ios-sdk-specs を追加します。
source 'https://github.com/shiguredo/sora-ios-sdk-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

# ビルドに失敗する可能性があるため、 use_frameworks! の使用は推奨しません。
# use_frameworks!

react_native_path = '../node_modules/react-native'

target 'HelloSora' do

  pod 'React', path: "#{react_native_path}"

  pod 'React-Core', :path => "#{react_native_path}/React"
  pod 'React-DevSupport', :path => "#{react_native_path}/React"

  pod 'React-RCTActionSheet', :path => "#{react_native_path}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{react_native_path}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{react_native_path}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{react_native_path}/Libraries/Image"
  pod 'React-RCTNetwork', :path => "#{react_native_path}/Libraries/Network"
  pod 'React-RCTWebSocket', :path => "#{react_native_path}/Libraries/WebSocket"
  pod 'React-RCTLinking', :path => "#{react_native_path}/Libraries/LinkingIOS"
  pod 'React-RCTSettings', :path => "#{react_native_path}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{react_native_path}/Libraries/Text"
  pod 'React-fishhook', :path => "#{react_native_path}/Libraries/fishhook"
  pod 'React-RCTVibration', :path => "#{react_native_path}//Libraries/Vibration"

  pod 'React-cxxreact', :path => "#{react_native_path}/ReactCommon/cxxreact"
  pod 'React-jsiexecutor', :path => "#{react_native_path}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{react_native_path}/ReactCommon/jsinspector"
  pod 'React-jsi', :path => "#{react_native_path}/ReactCommon/jsi"
  pod 'yoga', path: "#{react_native_path}/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "#{react_native_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{react_native_path}/third-party-podspecs/Folly.podspec"

  # このコメントの直下の行に、追加のreact-nativeネイティブモジュールがインストールされていきます。本ライブラリも以下に追加されます。
  # Add new pods below this line

  pod 'ReactNativeWebRTCKit', :path => "../node_modules/react-native-webrtc-kit"
end

# `libReact.a` の衝突を回避する処理を記述します。
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
